services:
  - type: web
    name: furniture-gallery-web
    runtime: static
    branch: main
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
